# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d164447e8a0d388f1dc5a84af5cc0c90e8df7fabe6b1d854ffff35ecf932cb9259dc89b6c8c0e8dcac79a087713c0da41fa62e983659819a30a65cd2704c3d1

test:
  secret_key_base: fb887df0de33c09f987e47c754f2f9435e0353f354b4ebcdc7bf6c68bb8de0accdfb7935d0ebb4c261e7d757f773df49a0ec96168820897a0ed0f4957fca11e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
